spring.application.name=qltc
spring.datasource.username=sa
spring.datasource.password=Admin@123
spring.datasource.url=jdbc:sqlserver://localhost:1433;TrustServerCertificate=true;database=QltcDb

# Auto update database structure base on entity
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

qltc.jwt.secret=thisisverysecret
qltc.jwt.issuer=localhost:8080

qltc.google.client_id=342915674625-egqemuqs7vee5433q5g54akqdu2o0k1r.apps.googleusercontent.com